project:
  type: website

website:
  title: "Muxin Hua"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Hiiiua
format:
  html:
    theme: solar
    css: styles.css

editor: visual

execute:
  freeze: auto
